medizininformatik-initiative/feasibility-gui

src/app/modules/querybuilder/components/querybuilder-editor/edit/edit-criterion/edit-criterion.component.scss, src/app/modules/querybuilder/components/querybuilder-editor/edit/edit-time-restriction/edit-time-restriction.component.html, src/app/modules/querybuilder/components/querybuilder-editor/edit/edit-time-restriction/edit-time-restriction.component.scss, src/app/modules/querybuilder/components/querybuilder-editor/edit/edit-value-filter/edit-value-filter.component.html, src/app/modules/querybuilder/components/querybuilder-editor/edit/edit-value-filter/edit-value-filter.component.scss, src/assets/i18n/de.json, src/assets/i18n/en.json
Issue #7 - hiding optional attributes in collapsed accordion
Issue #12 - add heading for time constraints
=> Issue #7 & Issue #12

Dockerfile, src/app/modules/querybuilder/components/querybuilder-editor/edit/edit-time-restriction/edit-time-restriction.component.html, src/app/modules/querybuilder/components/querybuilder-editor/edit/edit-time-restriction/edit-time-restriction.component.ts, src/app/modules/querybuilder/components/querybuilder-editor/edit/edit-value-filter-concept-line/edit-value-filter-concept-line.component.html, src/app/modules/querybuilder/components/querybuilder-editor/edit/edit-value-filter-concept-line/edit-value-filter-concept-line.component.scss, src/app/modules/querybuilder/components/querybuilder-editor/edit/edit-value-filter/edit-value-filter.component.html, src/app/modules/querybuilder/components/querybuilder-editor/edit/edit-value-filter/edit-value-filter.component.scss, src/app/modules/querybuilder/components/querybuilder-editor/edit/edit-value-filter/edit-value-filter.component.ts, src/app/modules/querybuilder/components/querybuilder-editor/querybuilder-editor.component.ts, src/app/modules/querybuilder/components/querybuilder-editor/result/result-simple/result-simple.component.ts
- Issue #54 - fix countdown timer when sending new query before finished
- Issue #20 - redundant codes are removed (interim solution)
- fix animation for mat-expansion-panel
- new nginx version
=>  various fixes

src/app/app.component.scss, src/app/layout/components/footer/footer.component.html, src/app/modules/querybuilder/components/querybuilder-editor/edit/edit-value-filter/edit-value-filter.component.scss, src/app/modules/querybuilder/components/querybuilder-editor/querybuilder-editor.component.scss, src/app/modules/querybuilder/components/querybuilder-editor/search/search-text-overlay-content/search-text-overlay-content.component.html, src/app/modules/querybuilder/components/querybuilder-editor/search/search-text-overlay-content/search-text-overlay-content.component.scss, src/app/modules/querybuilder/components/querybuilder-editor/search/search-tree-overlay-content/search-tree-overlay-content.component.scss
- Issue #27 - no dark background on popups 
- Issue #27 - no popup hint on free text search
- Issue #58 - change privacy link to forschen-fuer-gesundheit site
=> adjust popup behaviour

.github/dependabot.yml
This PR configures dependabot to weekly scan this repository's github actions and node packages for new version. It will automatically creates pull requests if an update is found.
=> Enable Dependabot for automatic dependency updates

CHANGELOG.md, src/assets/config/config.dev.json
=> #Release 1.0.0

src/app/core/auth/guards/role.guard.spec.ts, src/app/layout/components/footer/footer.component.spec.ts, src/app/layout/components/header/header.component.spec.ts, src/app/modules/querybuilder/components/querybuilder-editor/querybuilder-editor.component.scss, src/app/modules/querybuilder/components/querybuilder-editor/result/result-simple/result-simple.component.scss, src/app/modules/querybuilder/service/backend.service.ts
- change tooltip styling
- fix some tests
=> fix display behavior of the detail button

docker/deploy-config.json, docker/lang/de.json, docker/lang/en.json, src/app/config/app-config.model.ts, src/app/layout/components/app-layout/app-layout.component.spec.ts, src/app/layout/components/footer/footer.component.spec.ts, src/app/layout/components/header/header.component.spec.ts, src/app/modules/dashboard/components/dashboard/dashboard.component.html, src/app/modules/dashboard/components/dashboard/dashboard.component.ts, src/app/modules/options/components/options/options.component.spec.ts, src/app/service/feature.service.ts, src/assets/config/config.deploy.json, src/assets/config/config.dev.json, src/assets/i18n/de.json, src/assets/i18n/en.json
- add configurable link to Proposal Portal
- renaming classes translator variables
=> Issue #126 - confLink to Proposal Portal

src/app/modules/querybuilder/components/querybuilder-editor/edit/edit-criterion/edit-criterion.component.ts, src/app/modules/querybuilder/components/querybuilder-editor/querybuilder-editor.component.ts
- fix error on loading criterion with non selected attributes
=> Issue #131

docker/deploy-config.json, src/app/config/app-config.model.ts, src/app/layout/components/side-menu/side-menu.component.ts, src/app/modules/querybuilder/controller/ApiTranslator.ts, src/app/service/feature.service.ts, src/assets/config/config.deploy.json, src/assets/config/config.dev.json
Make hiding and displaying of dataselection in menu configurable
=> Make hiding and displaying of dataselection in menu configurable

docker/lang/de.json, docker/lang/en.json, src/app/core/components/snack-bar/snack-bar.component.html, src/app/core/components/snack-bar/snack-bar.component.scss, src/app/core/components/snack-bar/snack-bar.component.ts, src/app/modules/querybuilder/components/querybuilder-editor/display/display-criterion/display-criterion.component.ts, src/app/modules/querybuilder/components/querybuilder-editor/querybuilder-editor.component.html, src/app/modules/querybuilder/components/querybuilder-editor/querybuilder-editor.component.ts, src/app/modules/querybuilder/components/querybuilder-overview/querybuilder-overview.component.html, src/app/modules/querybuilder/components/querybuilder-overview/querybuilder-overview.component.ts, src/app/modules/querybuilder/components/querybuilder-overview/saved-queries/query-box-front/query-box-front.component.scss, src/app/modules/querybuilder/components/querybuilder-overview/saved-queries/saved-queries.component.html, src/app/modules/querybuilder/components/querybuilder-overview/saved-queries/saved-queries.component.ts, src/app/modules/querybuilder/components/querybuilder-overview/saved-queries/single-query/single-query.component.html, src/app/modules/querybuilder/components/querybuilder-overview/saved-queries/single-template/single-template.component.html, src/app/modules/querybuilder/components/querybuilder-overview/saved-queries/single-template/single-template.component.scss, src/app/modules/querybuilder/controller/TermEntry2CriterionTranslator.ts, src/app/modules/querybuilder/service/backend.service.ts, src/assets/i18n/de.json, src/assets/i18n/en.json
- show warning if loaded query has no context
- show warning if loaded template has no context or is otherwise invalid
=> Issue #144 - support loading non-compatible queries

src/app/modules/querybuilder/components/querybuilder-editor/edit/edit-criterion/edit-criterion.component.html, src/app/modules/querybuilder/components/querybuilder-editor/querybuilder-editor.component.html, src/app/modules/querybuilder/components/querybuilder-editor/querybuilder-editor.component.ts, src/app/modules/querybuilder/components/querybuilder-editor/result/result-simple/result-simple.component.ts, src/app/modules/querybuilder/components/querybuilder-editor/search/search-tree-overlay-content/search-tree-overlay-content.component.scss, src/app/modules/querybuilder/components/querybuilder-overview/saved-queries/query-box-end/query-box-end.component.ts, src/app/modules/querybuilder/components/querybuilder-overview/saved-queries/single-query/single-query.component.html
- show patient results for saved queries -fix height for search popup
=> -fix save-button for loading queries

src/app/model/ElasticSearch/ElasticSearchFilter/SearchTermFilter.ts, src/app/model/ElasticSearch/ElasticSearchResult/AbstractSearchResult.ts, src/app/model/ElasticSearch/ElasticSearchResult/AbstractTermHashContext.ts, src/app/model/ElasticSearch/ElasticSearchResult/ElasticSearchDetails/SearchTermDetails.ts, src/app/model/ElasticSearch/ElasticSearchResult/ElasticSearchDetails/SearchTermRelatives.ts, src/app/model/ElasticSearch/ElasticSearchResult/ElasticSearchDetails/SearchTermTranslation.ts, src/app/model/ElasticSearch/ElasticSearchResult/ElasticSearchList/SearchTermListItem.ts, src/app/model/ElasticSearch/ElasticSearchResult/ElasticSearchList/SearchTermResultList.ts, src/app/modules/querybuilder/components/querybuilder-editor/search/search-text-overlay-content/search-text-overlay-content.component.ts, src/app/modules/querybuilder/service/backend.service.ts, src/app/service/CriterionService/CreateCriterion.service.ts, src/app/service/CriterionService/edit-criterion.service.ts, src/app/service/ElasticSearch.service.ts
- new data model for Elastic Search
- new backend endpoints for getting search results from Elastic Search
- new services for translating Elastic Search results to TermEntries and Criteria
=> Elastic search service

CHANGELOG.md, docker/deploy-config.json, src/app/modules/querybuilder/components/querybuilder-overview/querybuilder-overview.component.ts, src/app/service/StructuredQuery2UIQueryTranslator.service.ts, src/assets/config/config.dev.json
##Bugfix
- Add referencedCriteria correctly to selectedCriteria when loading or importing a query
=> Release v5.0.0 alpha.3

CHANGELOG.md, docker/deploy-config.json, src/app/modules/querybuilder/components/querybuilder-overview/querybuilder-overview.component.ts, src/app/service/StructuredQuery2UIQueryTranslator.service.ts, src/assets/config/config.dev.json
* Custom Internal Data Format for Structured Queries:
-	Developed an internal data format specifically for Structured Queries, a data representation developed by our team.
* Improved Data Model Structure:
-	Restructured the data model for better representation of Structured Queries through class and folder organization.
* Utilization of Abstract Classes and General Concepts:
-	Incorporated abstract classes and general concepts into the data model for improved versatility.
* Simplified Attribute and Value Filter Types:
-	Cleaned up attribute and value filter types for easier use.
* Type Checking Service Implementation:
-	Added a service to perform type validation checks for attribute and value filter types.
* Structured Query Translation Service
-	New translation services for translating …
=> Release v5.0.0

CHANGELOG.md, docker/deploy-config.json, src/app/modules/querybuilder/components/querybuilder-editor/querybuilder-editor.component.ts, src/app/service/CriterionService/CreateCriterion.service.ts, src/assets/config/config.dev.json
- fix send button check for invalid criteria
- add context to loaded criteria even if its invalid
=> Release v5.0.1

docker/lang/de.json, docker/lang/en.json, src/app/layout/components/header/header.component.html, src/app/modules/data-selection/components/data-selection.component.html, src/app/modules/data-selection/components/display-profiles/data-selection-boxes/data-selection-boxes.component.html, src/app/modules/data-selection/components/display-profiles/data-selection-boxes/data-selection-boxes.component.scss, src/app/modules/data-selection/components/display-profiles/data-selection-boxes/data-selection-boxes.component.ts, src/app/modules/data-selection/components/edit-fields-modal/edit-fields-modal.component.html, src/app/modules/data-selection/components/edit-fields-modal/edit-fields-modal.component.scss, src/app/modules/data-selection/components/edit-fields-modal/edit-fields-modal.component.ts, src/app/modules/querybuilder/components/querybuilder-editor/pre-stage/pre-stage.component.html, src/app/modules/querybuilder/components/querybuilder-editor/search/search.component.html, src/app/modules/querybuilder/components/querybuilder-editor/search/search.component.scss, src/app/shared/components/filter-chips/filter-chips.component.html, src/app/shared/components/reference-criteria-box/reference-criteria-box.component.ts, src/assets/i18n/de.json, src/assets/i18n/en.json
Includes multiple smaller bugfixes, inclduding:
- Adding header info to dataselection and search
- Adding missing translations
- Adding additional information to add field when none are selected in dse profile
- Temporarily add language switch to make german available on english browser
=> 235 collection small bugfixes UI

package-lock.json, package.json, src/app/layout/font-awesome-icons.ts, src/app/modules/feasibility-query/service/backend.service.ts, src/app/shared/components/header-description/header-description.component.scss, src/app/shared/components/menu/menu.component.html, src/app/shared/components/menu/menu.component.scss, src/app/shared/models/TableData/Adapter/SearchTermListEntryAdapter.ts, src/app/shared/service/Menu/Criterion/CriterionMenuItems.service.ts, src/app/shared/service/Menu/DataSelection/MenuServiceDataSelection.service.ts, src/app/shared/service/Menu/RefrenceCriterion/ReferenceCriterionMenuItems.service.ts
small bugfixes:
- make header descriptions more visible
- show "?" when availability = 0 - as this is more accurate for now
- fix error loading large query - chunk get profile data by ids
- change option menu icons
- change menu icon
- make options in options menu more distinguishable as non-button
=> 290 small bugfixes

CHANGELOG.md, docker/deploy-config.json, docker/lang/de.json, docker/lang/en.json, src/app/modules/data-selection/data-selection.module.ts, src/app/shared/components/filter-chips/filter-chips.component.html, src/app/shared/components/shared-components.module.ts, src/app/shared/models/FilterChips/Adapter/DataSelection/FilterChipDataSelectionAdapter.ts, src/app/shared/models/FilterChips/FilterChipBuilder.ts, src/app/shared/pipes/DisplayTranslationPipe .ts, src/app/shared/service/FilterChips/DataSelection/DataSelectionFilterChips.service.ts, src/assets/config/config.dev.json
* New Design
- Introduced a completely redesigned user interface for an improved user experience.
- Updated visual elements, including color schemes, typography, and iconography, to create a modern and cohesive look.
* New Data Model
- Implemented a new data model to enhance data handling and processing capabilities.
* New Component Structure
- Reorganized the component structure for better modularity and maintainability.
* New Process Infrastructure
- Developed a new process infrastructure to optimize system performance and scalability.
- Redesigned the information architecture to make content more discoverable and ensure logical organization of information throughout the platform.
* New Backend Endpoints
- Added new backend endpoints to support additional functionalities and improve API …
=> Release v6.0.0

.github/workflows/ci.yml, CHANGELOG.md, docker/deploy-config.json, docker/lang/de.json, src/app/shared/models/FilterChips/Adapter/FilterChipConceptAdapter.ts, src/app/shared/models/FilterChips/Adapter/FilterChipQuantityAdapter.ts, src/app/shared/models/FilterChips/Adapter/FilterChipTimeRestrictionAdapter.ts, src/assets/config/config.dev.json, src/assets/i18n/de.json
* Display data for all chip types correctly
* small language fixes
* Increased pencil size icon in menu
=> Release v6.0.1

CHANGELOG.md, docker/deploy-config.json, src/app/model/Result/QueryResult.ts, src/app/modules/feasibility-query/components/result/simple-result/simple-result.component.ts, src/app/service/FeasibilityQueryResult.service.ts, src/assets/config/config.dev.json
* Getting polling time from Feature-Provider-Service instead of Feature-Service
* Repeat polling until end of timer, regardless Null results in between
=> Release v6.0.2

CHANGELOG.md, docker/deploy-config.json, src/assets/config/config.dev.json
* Removed hashes in result details modal and replaced them with DIZ n-1 ([#313](https://github.com/medizininformatik-initiative/feasibility-gui/issues/313)).
* Fixed error message display and refactored snackbar service ([#310](https://github.com/medizininformatik-initiative/feasibility-gui/issues/310)).
* Resolved inconsistency between summary and detail results ([#303](https://github.com/medizininformatik-initiative/feasibility-gui/issues/303), [#304](https://github.com/medizininformatik-initiative/feasibility-gui/issues/304)).
* Refactored feasibility query result service into smaller services ([#329](https://github.com/medizininformatik-initiative/feasibility-gui/issues/329)).
* Updated result details only once per feasibility query …
=> Release v6.0.4-alpha

CHANGELOG.md, docker/deploy-config.json, src/app/service/CriteriaProfileData/Mapper/ValueDefinitionsResultMapper.ts, src/app/service/FeasibilityQuery/Result/Polling/PollingManager.service.ts, src/assets/config/config.dev.json
* fixed wrong key for valueDefinition mapping
=> Release v6.0.5

src/app/modules/feasibility-query/components/editor/stage/consent-switches/consent-switches.component.html, src/app/modules/feasibility-query/components/editor/stage/consent-switches/consent-switches.component.ts, src/assets/i18n/de.json, src/assets/i18n/en.json
added consent translation by using code as the key for the translation value
=> added consent translation

CHANGELOG.md, docker/deploy-config.json, src/assets/config/config.dev.json
* Fixed index increment issue with parentheses ([#313])
* Reduced container height ([#343])
* Corrected consent subscription ([#344])
* Defined and applied interfaces ([#333])
* Refactored CriterionValidationService into smaller services ([#332])
* Merged two criterion creation services into one ([#326])
* Added transtlation for consent text ([#263])
=> Release v6.0.7

CHANGELOG.md, docker/deploy-config.json, src/assets/config/config.dev.json
* Prevent constant openings of modal after downloading query  ([#363](https://github.com/medizininformatik-initiative/feasibility-gui/issues/363))
* Adjustments for german UI translation
=> Release v6.0.9

CHANGELOG.md, docker/deploy-config.json, src/assets/config/config.dev.json
* switch to API v5
* switch date display to european format ([#371](https://github.com/medizininformatik-initiative/feasibility-gui/issues/371))
* new save dialog with checkboxes for cohort and data selection ([#354](https://github.com/medizininformatik-initiative/feasibility-gui/issues/354))
* new TypeGuard and Type Assertion functionality for type safety during compiling time ([#360](https://github.com/medizininformatik-initiative/feasibility-gui/issues/360))
* fixes for various minor issues and clean up code
=> Release v6.1.0

CHANGELOG.md, docker/deploy-config.json, src/assets/config/config.dev.json
* Added new editor pages for Criterion and Profile ([#373](https://github.com/medizininformatik-initiative/feasibility-gui/issues/373))
* Implemented reference solution as per related issue ([#309](https://github.com/medizininformatik-initiative/feasibility-gui/issues/309))
* Introduced updated data model ([#373](https://github.com/medizininformatik-initiative/feasibility-gui/issues/373))
* Adjusted CSS for indentation in tree view ([#350](https://github.com/medizininformatik-initiative/feasibility-gui/issues/350))
* Increased ElasticSearch visualization limit from 20 to 50 matches ([#352](https://github.com/medizininformatik-initiative/feasibility-gui/issues/352))
* fixes for various minor issues and clean up code
=> Release 6.2.0-alpha

CHANGELOG.md, docker/deploy-config.json, src/assets/config/config.dev.json
* Implemented loading of reference profile lists ([#381](https://github.com/medizininformatik-initiative/feasibility-gui/issues/381))
* Added support for single feature patient profiles ([#380](https://github.com/medizininformatik-initiative/feasibility-gui/issues/380))
* Prevent Maximum Quantity Value from Being Less Than Minimum Quantity ([#374](https://github.com/medizininformatik-initiative/feasibility-gui/issues/374))
* Completed rework of Core Service for improved internal structure ([#387](https://github.com/medizininformatik-initiative/feasibility-gui/issues/387))
* Fix downloading an uploaded CRTDL with filter again ([#382](https://github.com/medizininformatik-initiative/feasibility-gui/issues/382))
* Fixing various small issues …
=> Release v6.2.0

CHANGELOG.md, docker/deploy-config.json, src/assets/config/config.dev.json
* **About Page** with system version information (UI, Backend, Ontology) [#403](https://github.com/medizininformatik-initiative/feasibility-gui/issues/403)
* Updated **language files** in `src/assets/i18n` [#393](https://github.com/medizininformatik-initiative/feasibility-gui/issues/393), [#399](https://github.com/medizininformatik-initiative/feasibility-gui/issues/399), [#400](https://github.com/medizininformatik-initiative/feasibility-gui/issues/400)
* Ensured **all CI tests** run successfully [#405](https://github.com/medizininformatik-initiative/feasibility-gui/issues/405)
* Fix snackbar message when cancel downloading [#398](https://github.com/medizininformatik-initiative/feasibility-gui/issues/398)
=> Release 6.3.1

CHANGELOG.md, docker/deploy-config.json, docker/lang/de.json, docker/lang/en.json, src/app/shared/components/save-file-modal/save-file-modal.component.html, src/assets/config/config.dev.json, src/assets/i18n/de.json, src/assets/i18n/en.json
* add missing lang entry
* fix auth config
=> Release v6.3.2

src/app/layout/components/header/header.component.html, src/app/layout/components/header/header.component.scss, src/app/layout/components/header/header.component.ts, src/app/layout/font-awesome-icons.ts, src/assets/i18n/de.json, src/assets/i18n/en.json
This pull request updates the header component to add a new "Antragsportal" (proposal portal) link
**Header UI and functionality improvements:**
* Added a new "Antragsportal" link to the header, which opens the proposal portal in a new tab when clicked, and styled it to look like a link with hover effects
* Added missing translation to header component
=> 368 add link to proposal portal

src/app/layout/font-awesome-icons.ts, src/app/modules/feasibility-query/components/search/search.component.ts, src/app/shared/components/table/table.component.html, src/app/shared/components/table/table.component.scss, src/app/shared/models/TableData/Adapter/CriteriaListEntryAdapter.ts, src/assets/i18n/de.json, src/assets/i18n/en.json
- Added icon to table component
- Extended adapter
- Added missing tooltips
=> 413 display tree icon next to each search result

CHANGELOG.md, docker/deploy-config.json, src/assets/config/config.dev.json
* Changed description of Feature Selection [#438](https://github.com/medizininformatik-initiative/feasibility-gui/issues/438)
* Refactor user profile handling across services and components [#436](https://github.com/medizininformatik-initiative/feasibility-gui/pull/436)
* Add AuthToken and HttpError interceptors for improved HTTP request handling [#435](https://github.com/medizininformatik-initiative/feasibility-gui/pull/435)
=> Release v6.3.5

CHANGELOG.md, docker/deploy-config.json, src/assets/config/config.dev.json
* Updated UI profile to support multiple value sets and criteria sets for feasibility [#425](https://github.com/medizininformatik-initiative/feasibility-gui/issues/425)
* Redesigned snackbar [#447](https://github.com/medizininformatik-initiative/feasibility-gui/issues/447)
* Added feedback through the snackbar on profile edit [#448](https://github.com/medizininformatik-initiative/feasibility-gui/issues/448)
* Prevent field tree from collapsing on every selection [#445](https://github.com/medizininformatik-initiative/feasibility-gui/issues/445)
* Ensure patient profile always remains part of the data extraction [#449](https://github.com/medizininformatik-initiative/feasibility-gui/issues/449)
* Allow unsetting/deleting of filters [#442](https://github.com/medizininformatik-initiative/feasib …
=> Release v6.3.6
